chromeRemoteURL: http://192.168.188.103:9222/json/version

CacheDir: ./cache
DownDir: ./download
HttpProxy: http://192.168.188.1:3128
MaxDownloadWorkers: 2
DirectDownloadFirst: true
ListCode: [
  407019,
  407014,

]

SingleCode: [
]
# 默认下载视频分辨率，如不配置或找不到对应分辨率，默认下载最高分辨率 (支持: 480p, 720p, 1080p)
VideoResolution: "720p"

