services:
  app:
    build: .
    container_name: ubuntu
    hostname: ubuntu
    shm_size: 128mb
    restart: always
    environment:
      # user root
      - HTTP_PASSWORD=Password
      - HTTP_PROXY="http://192.168.188.1:3128"
      - HTTPS_PROXY="http://192.168.188.1:3128"
    volumes:
      - ./chrome-stream.conf:/etc/supervisor/modules-enabled/99-chrome-stream.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 2080:80
      - 9222:9000


networks:
  default:
    external: true
    name: share